// ⚠️ Archivo generado a partir de "Base_de_datos_final.xlsx" — no hardcodeado a mano.
// Para modificar el inventario, editá este archivo o regenéralo desde una fuente de datos externa.

export type Condition = "nueva" | "usada";

export type Category = {
  slug: string;
  name: string;
  description: string;
  image: string;
};

export type Specification = {
  label: string;
  value?: string;
};

export type Product = {
  id: string;
  slug: string;
  name: string;
  condition: Condition;
  category: string;
  subcategory?: string;
  brand: string;
  articleNumber: number;
  description: string;
  specifications: Specification[];
  images: string[];
  featured: boolean;
  availability: "Disponible" | "Reservada" | "Consultar";
  price: number | null;
};

// ---------------------------------------------------------------------------
// CATEGORÍAS (generadas a partir de "Familia de Producto" del Excel)
// ---------------------------------------------------------------------------
export const categories: Category[] = [
  {
    slug: "bombas",
    name: "Bombas",
    description: "Bombas centrífugas, de vacío, positivas y peristálticas usadas.",
    image: "/images/inventario/art-09-7.jpg",
  },
  {
    slug: "transportes",
    name: "Transportes",
    description: "Transportadores sin fin y cintas transportadoras.",
    image: "/images/inventario/art-01-1.jpg",
  },
  {
    slug: "tanques",
    name: "Tanques",
    description: "Tanques, reactores y recipientes de distintos materiales y capacidades.",
    image: "/images/inventario/art-26-31.jpg",
  },
  {
    slug: "piping",
    name: "Piping",
    description: "Válvulas, accesorios y elementos de cañerías industriales.",
    image: "/images/inventario/art-19-25.jpg",
  },
  {
    slug: "ventiladores",
    name: "Ventiladores",
    description: "Ventiladores y extractores industriales.",
    image: "/images/inventario/art-17-23.jpg",
  },
  {
    slug: "intercambiadores-de-calor",
    name: "Intercambiadores de Calor",
    description: "Intercambiadores casco y tubo, radiadores y equipos térmicos.",
    image: "/images/inventario/art-27-34.jpg",
  },
  {
    slug: "motorreductores",
    name: "Motorreductores",
    description: "Motorreductores de distintas potencias y marcas.",
    image: "/images/inventario/art-52-78.jpg",
  },
  {
    slug: "motores",
    name: "Motores",
    description: "Motores eléctricos varios.",
    image: "/images/inventario/art-54-80.jpg",
  },
  {
    slug: "gruas",
    name: "Grúas",
    description: "Grúas pluma y equipos de izaje.",
    image: "/images/inventario/art-25-29.jpg",
  },
  {
    slug: "otros-equipos",
    name: "Otros Equipos",
    description: "Filtros, tamices, soldadoras, pistones y equipos varios.",
    image: "/images/inventario/art-04-3.jpg",
  },
];

// ---------------------------------------------------------------------------
// PRODUCTOS (inventario real, generado desde "Base_de_datos_final.xlsx")
// ---------------------------------------------------------------------------
export const products: Product[] = [
  {
    id: "1",
    slug: "transportador-sin-fin-tornillo-art-01",
    name: "Transportador Sin Fin (Tornillo) — Art. 01",
    condition: "usada",
    category: "transportes",
    subcategory: "sin Fines",
    brand: "Consultar",
    articleNumber: 1,
    description: "Buen estado General.: camisa y espira de Acero inoxidable",
    specifications: [
      { label: "Material constructivo", value: "Acero Inoxidable" },
      { label: "Dimensiones", value: "Diametro 9\"- Largo Aprox: 3 mts" },
      { label: "Familia", value: "Transportes" },
      { label: "Subfamilia", value: "sin Fines" },
    ],
    images: ["/images/inventario/art-01-1.jpg"],
    featured: true,
    availability: "Disponible",
    price: null,
  },
  {
    id: "2",
    slug: "transportador-sin-fin-tornillo-art-02",
    name: "Transportador Sin Fin (Tornillo) — Art. 02",
    condition: "usada",
    category: "transportes",
    subcategory: "sin Fines",
    brand: "Consultar",
    articleNumber: 2,
    description: "Equipo usado de la familia Transportes, subfamilia sin Fines. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "Diametro 8\" - Largo Aprox: 3,5 mts" },
      { label: "Familia", value: "Transportes" },
      { label: "Subfamilia", value: "sin Fines" },
    ],
    images: ["/images/inventario/art-02-2.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "3",
    slug: "transportador-sin-fin-tornillo-art-03",
    name: "Transportador Sin Fin (Tornillo) — Art. 03",
    condition: "usada",
    category: "transportes",
    subcategory: "sin Fines",
    brand: "Consultar",
    articleNumber: 3,
    description: "Mezclador /rompedor: doble",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "Diametro 4\"_ largo 3 mts" },
      { label: "Familia", value: "Transportes" },
      { label: "Subfamilia", value: "sin Fines" },
    ],
    images: ["/images/inventario/art-03-1.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "4",
    slug: "bateria-de-filtros-art-04",
    name: "Batería de Filtros — Art. 04",
    condition: "usada",
    category: "otros-equipos",
    subcategory: "Filtros",
    brand: "Consultar",
    articleNumber: 4,
    description: "Bateria de 3 filtros",
    specifications: [
      { label: "Material constructivo", value: "Acero Inoxidable" },
      { label: "Dimensiones", value: "Diametro 3\"" },
      { label: "Familia", value: "Otros Equipos" },
      { label: "Subfamilia", value: "Filtros" },
    ],
    images: ["/images/inventario/art-04-3.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "5",
    slug: "transportador-sin-fin-tornillo-art-05",
    name: "Transportador Sin Fin (Tornillo) — Art. 05",
    condition: "usada",
    category: "transportes",
    subcategory: "sin Fines",
    brand: "Consultar",
    articleNumber: 5,
    description: "Equipo usado de la familia Transportes, subfamilia sin Fines. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "Acero Inoxidable" },
      { label: "Dimensiones", value: "Diametro 9\"- Largo Aprox 2 mts" },
      { label: "Familia", value: "Transportes" },
      { label: "Subfamilia", value: "sin Fines" },
    ],
    images: ["/images/inventario/art-05-4.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "6",
    slug: "transportador-sin-fin-tornillo-art-06",
    name: "Transportador Sin Fin (Tornillo) — Art. 06",
    condition: "usada",
    category: "transportes",
    subcategory: "sin Fines",
    brand: "Consultar",
    articleNumber: 6,
    description: "Equipo usado de la familia Transportes, subfamilia sin Fines. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "Acero Inoxidable" },
      { label: "Dimensiones", value: "Diametro 12\"- Largo Aprox 1 mts" },
      { label: "Familia", value: "Transportes" },
      { label: "Subfamilia", value: "sin Fines" },
    ],
    images: ["/images/inventario/art-06-4.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "7",
    slug: "tamiz-industrial-art-07",
    name: "Tamiz Industrial — Art. 07",
    condition: "usada",
    category: "otros-equipos",
    subcategory: "tamices",
    brand: "Consultar",
    articleNumber: 7,
    description: "Base de tamices con motor",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Familia", value: "Otros Equipos" },
      { label: "Subfamilia", value: "tamices" },
    ],
    images: ["/images/inventario/art-07-5.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "8",
    slug: "cinta-transportadora-art-08",
    name: "Cinta Transportadora — Art. 08",
    condition: "usada",
    category: "transportes",
    subcategory: "Cintas",
    brand: "Consultar",
    articleNumber: 8,
    description: "Cinta transporadora inclinada movil",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "Ancho : 50 cm : largo aprox 5 mts" },
      { label: "Familia", value: "Transportes" },
      { label: "Subfamilia", value: "Cintas" },
    ],
    images: ["/images/inventario/art-08-6.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "9",
    slug: "bomba-centrifuga-art-09",
    name: "Bomba Centrífuga — Art. 09",
    condition: "usada",
    category: "bombas",
    subcategory: "Centrifugas",
    brand: "Consultar",
    articleNumber: 9,
    description: "Usada a revisar: completa",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "2x3-10" },
      { label: "Familia", value: "Bombas" },
      { label: "Subfamilia", value: "Centrifugas" },
    ],
    images: ["/images/inventario/art-09-7.jpg"],
    featured: true,
    availability: "Disponible",
    price: null,
  },
  {
    id: "10",
    slug: "bomba-centrifuga-art-10",
    name: "Bomba Centrífuga — Art. 10",
    condition: "usada",
    category: "bombas",
    subcategory: "Centrifugas",
    brand: "Consultar",
    articleNumber: 10,
    description: "Usada a revisar: completa",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "2x3-10" },
      { label: "Familia", value: "Bombas" },
      { label: "Subfamilia", value: "Centrifugas" },
    ],
    images: ["/images/inventario/art-10-7.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "11",
    slug: "bomba-de-desplazamiento-positivo-art-11",
    name: "Bomba de Desplazamiento Positivo — Art. 11",
    condition: "usada",
    category: "bombas",
    subcategory: "Positivas",
    brand: "Consultar",
    articleNumber: 11,
    description: "usada: operativa industria alimenticia",
    specifications: [
      { label: "Material constructivo", value: "Acero Inoxidable" },
      { label: "Dimensiones", value: "3x3-6" },
      { label: "Familia", value: "Bombas" },
      { label: "Subfamilia", value: "Positivas" },
    ],
    images: ["/images/inventario/art-11-8.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "12",
    slug: "bomba-de-desplazamiento-positivo-art-12",
    name: "Bomba de Desplazamiento Positivo — Art. 12",
    condition: "usada",
    category: "bombas",
    subcategory: "Positivas",
    brand: "Consultar",
    articleNumber: 12,
    description: "usada: operativa industria alimenticia",
    specifications: [
      { label: "Material constructivo", value: "Acero Inoxidable" },
      { label: "Dimensiones", value: "3x3-6" },
      { label: "Familia", value: "Bombas" },
      { label: "Subfamilia", value: "Positivas" },
    ],
    images: ["/images/inventario/art-12-9.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "13",
    slug: "bomba-de-vacio-art-13",
    name: "Bomba de Vacío — Art. 13",
    condition: "usada",
    category: "bombas",
    subcategory: "Vacio",
    brand: "Consultar",
    articleNumber: 13,
    description: "Doble succion",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "2\" entrada" },
      { label: "Familia", value: "Bombas" },
      { label: "Subfamilia", value: "Vacio" },
    ],
    images: ["/images/inventario/art-13-10.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "14",
    slug: "bomba-de-vacio-art-14",
    name: "Bomba de Vacío — Art. 14",
    condition: "usada",
    category: "bombas",
    subcategory: "Vacio",
    brand: "Consultar",
    articleNumber: 14,
    description: "simple succion",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "2\" entrada" },
      { label: "Familia", value: "Bombas" },
      { label: "Subfamilia", value: "Vacio" },
    ],
    images: ["/images/inventario/art-14-11.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "15",
    slug: "bomba-centrifuga-art-15",
    name: "Bomba Centrífuga — Art. 15",
    condition: "usada",
    category: "bombas",
    subcategory: "Centrifugas",
    brand: "Consultar",
    articleNumber: 15,
    description: "Revestida",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "1,5x2-8\"" },
      { label: "Familia", value: "Bombas" },
      { label: "Subfamilia", value: "Centrifugas" },
    ],
    images: ["/images/inventario/art-15-19.jpg", "/images/inventario/art-15-20.jpg", "/images/inventario/art-15-21.jpg"],
    featured: true,
    availability: "Disponible",
    price: null,
  },
  {
    id: "16",
    slug: "soldadora-industrial-art-16",
    name: "Soldadora Industrial — Art. 16",
    condition: "usada",
    category: "otros-equipos",
    subcategory: "Soldadora",
    brand: "Consultar",
    articleNumber: 16,
    description: "Soldadora industrial",
    specifications: [
      { label: "Familia", value: "Otros Equipos" },
      { label: "Subfamilia", value: "Soldadora" },
    ],
    images: ["/images/inventario/art-16-22.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "17",
    slug: "ventilador-industrial-art-17",
    name: "Ventilador Industrial — Art. 17",
    condition: "usada",
    category: "ventiladores",
    subcategory: "Ventilador",
    brand: "Consultar",
    articleNumber: 17,
    description: "Equipo usado de la familia Ventiladores, subfamilia Ventilador. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "10 HP" },
      { label: "Familia", value: "Ventiladores" },
      { label: "Subfamilia", value: "Ventilador" },
    ],
    images: ["/images/inventario/art-17-23.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "18",
    slug: "equipo-industrial-otros-art-18",
    name: "Equipo Industrial — Otros — Art. 18",
    condition: "usada",
    category: "otros-equipos",
    brand: "Consultar",
    articleNumber: 18,
    description: "Equipo usado de la familia Otros Equipos. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Familia", value: "Otros Equipos" },
    ],
    images: ["/images/inventario/art-18-24.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "19",
    slug: "lote-de-valvulas-esfericas-art-19",
    name: "Lote de Válvulas Esféricas — Art. 19",
    condition: "usada",
    category: "piping",
    subcategory: "Valvulas Esfericas",
    brand: "Consultar",
    articleNumber: 19,
    description: "Usadas y reparadas",
    specifications: [
      { label: "Material constructivo", value: "Acero Inoxidable" },
      { label: "Dimensiones", value: "de 1,5\" - 2\" y 3\"" },
      { label: "Familia", value: "Piping" },
      { label: "Subfamilia", value: "Valvulas Esfericas" },
    ],
    images: ["/images/inventario/art-19-25.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "20",
    slug: "bomba-centrifuga-art-20",
    name: "Bomba Centrífuga — Art. 20",
    condition: "usada",
    category: "bombas",
    subcategory: "Centrifugas",
    brand: "Consultar",
    articleNumber: 20,
    description: "Estado general bueno",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "3x4-13\"" },
      { label: "Familia", value: "Bombas" },
      { label: "Subfamilia", value: "Centrifugas" },
    ],
    images: ["/images/inventario/art-20-26.jpg", "/images/inventario/art-20-27.jpg"],
    featured: true,
    availability: "Disponible",
    price: null,
  },
  {
    id: "21",
    slug: "ventilador-industrial-art-21",
    name: "Ventilador Industrial — Art. 21",
    condition: "usada",
    category: "ventiladores",
    brand: "Consultar",
    articleNumber: 21,
    description: "Estado general bueno: salida de 20x20 cm",
    specifications: [
      { label: "Material constructivo", value: "Acero Inoxidable" },
      { label: "Dimensiones", value: "Diametro 400 mm - Potencia 3 HP" },
      { label: "Familia", value: "Ventiladores" },
    ],
    images: ["/images/inventario/art-21-28.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "22",
    slug: "ventilador-industrial-art-22",
    name: "Ventilador Industrial — Art. 22",
    condition: "usada",
    category: "ventiladores",
    brand: "Consultar",
    articleNumber: 22,
    description: "Entrada de 3\"",
    specifications: [
      { label: "Material constructivo", value: "Acero Inoxidable" },
      { label: "Dimensiones", value: "Diametro 300 mm - Potencia 3 HP" },
      { label: "Familia", value: "Ventiladores" },
    ],
    images: ["/images/inventario/art-22-28.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "23",
    slug: "bomba-peristaltica-art-23",
    name: "Bomba Peristáltica — Art. 23",
    condition: "usada",
    category: "bombas",
    subcategory: "peristaltica",
    brand: "Consultar",
    articleNumber: 23,
    description: "Equipo usado de la familia Bombas, subfamilia peristaltica. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "Bomba peristaltica de 1/2\" de entrada y salida: 1/2 HP" },
      { label: "Familia", value: "Bombas" },
      { label: "Subfamilia", value: "peristaltica" },
    ],
    images: ["/images/inventario/art-23-28.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "24",
    slug: "bomba-peristaltica-art-24",
    name: "Bomba Peristáltica — Art. 24",
    condition: "usada",
    category: "bombas",
    subcategory: "peristaltica",
    brand: "Consultar",
    articleNumber: 24,
    description: "Equipo usado de la familia Bombas, subfamilia peristaltica. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "Bomba peristaltica de 1/2\" de entrada y salida: 1/2 HP" },
      { label: "Familia", value: "Bombas" },
      { label: "Subfamilia", value: "peristaltica" },
    ],
    images: ["/images/inventario/art-24-28.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "25",
    slug: "grua-pluma-art-25",
    name: "Grúa Pluma — Art. 25",
    condition: "usada",
    category: "gruas",
    subcategory: "Pluma",
    brand: "Consultar",
    articleNumber: 25,
    description: "Consultar datos tecnicos: Estado Operativa",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "Pluma de 100 mts de altura" },
      { label: "Familia", value: "Grúas" },
      { label: "Subfamilia", value: "Pluma" },
    ],
    images: ["/images/inventario/art-25-29.jpg", "/images/inventario/art-25-30.jpg", "/images/inventario/art-25-32.jpg", "/images/inventario/art-25-33.jpg"],
    featured: true,
    availability: "Disponible",
    price: null,
  },
  {
    id: "26",
    slug: "reactor-con-camisa-art-26",
    name: "Reactor con Camisa — Art. 26",
    condition: "usada",
    category: "tanques",
    subcategory: "reactor",
    brand: "Consultar",
    articleNumber: 26,
    description: "Reactor con camisa para vapor: cant 2",
    specifications: [
      { label: "Material constructivo", value: "Acero Inoxidable" },
      { label: "Dimensiones", value: "100 litros" },
      { label: "Familia", value: "Tanques" },
      { label: "Subfamilia", value: "reactor" },
    ],
    images: ["/images/inventario/art-26-31.jpg"],
    featured: true,
    availability: "Disponible",
    price: null,
  },
  {
    id: "27",
    slug: "radiador-industrial-art-27",
    name: "Radiador Industrial — Art. 27",
    condition: "usada",
    category: "intercambiadores-de-calor",
    subcategory: "radiadores",
    brand: "Consultar",
    articleNumber: 27,
    description: "Radiadores de Ac carbono galvanizado: secador de aire para frigorifico",
    specifications: [
      { label: "Material constructivo", value: "galvanizado" },
      { label: "Dimensiones", value: "Modulos de 2 mts alto  x 3mts de ancho" },
      { label: "Familia", value: "Intercambiadores de Calor" },
      { label: "Subfamilia", value: "radiadores" },
    ],
    images: ["/images/inventario/art-27-34.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "28",
    slug: "tanque-horizontal-art-28",
    name: "Tanque Horizontal — Art. 28",
    condition: "usada",
    category: "tanques",
    subcategory: "horizontal",
    brand: "Consultar",
    articleNumber: 28,
    description: "Equipo usado de la familia Tanques, subfamilia horizontal. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "15000 litros: 2 mts diametro x 5mts de largo aprox" },
      { label: "Familia", value: "Tanques" },
      { label: "Subfamilia", value: "horizontal" },
    ],
    images: ["/images/inventario/art-28-35.jpg"],
    featured: true,
    availability: "Disponible",
    price: null,
  },
  {
    id: "29",
    slug: "tanque-industrial-art-29",
    name: "Tanque Industrial — Art. 29",
    condition: "usada",
    category: "tanques",
    brand: "Consultar",
    articleNumber: 29,
    description: "Equipo usado de la familia Tanques. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "Acero Inoxidable" },
      { label: "Dimensiones", value: "20000 litros con patas" },
      { label: "Familia", value: "Tanques" },
    ],
    images: ["/images/inventario/art-29-36.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "30",
    slug: "tanque-industrial-art-30",
    name: "Tanque Industrial — Art. 30",
    condition: "usada",
    category: "tanques",
    brand: "Consultar",
    articleNumber: 30,
    description: "Equipo usado de la familia Tanques. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "PVC" },
      { label: "Dimensiones", value: "500 litros" },
      { label: "Familia", value: "Tanques" },
    ],
    images: ["/images/inventario/art-30-38.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "31",
    slug: "tanque-industrial-art-31",
    name: "Tanque Industrial — Art. 31",
    condition: "usada",
    category: "tanques",
    brand: "Consultar",
    articleNumber: 31,
    description: "Equipo usado de la familia Tanques. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "PVC" },
      { label: "Dimensiones", value: "500 litros" },
      { label: "Familia", value: "Tanques" },
    ],
    images: ["/images/inventario/art-31-39.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "32",
    slug: "molino-industrial-art-32",
    name: "Molino Industrial — Art. 32",
    condition: "usada",
    category: "otros-equipos",
    brand: "Consultar",
    articleNumber: 32,
    description: "Equipo usado de la familia Otros Equipos. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "molinos" },
      { label: "Familia", value: "Otros Equipos" },
    ],
    images: ["/images/inventario/art-32-42.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "33",
    slug: "tanque-industrial-art-33",
    name: "Tanque Industrial — Art. 33",
    condition: "usada",
    category: "tanques",
    brand: "Consultar",
    articleNumber: 33,
    description: "Equipo usado de la familia Tanques. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "PRFV" },
      { label: "Dimensiones", value: "10000 litros" },
      { label: "Familia", value: "Tanques" },
    ],
    images: ["/images/inventario/art-33-44.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "34",
    slug: "tanque-industrial-art-34",
    name: "Tanque Industrial — Art. 34",
    condition: "usada",
    category: "tanques",
    brand: "Consultar",
    articleNumber: 34,
    description: "Equipo usado de la familia Tanques. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "Acero Inoxidable" },
      { label: "Dimensiones", value: "Separador: diametro 1.4 mts Altura 2,5 mts" },
      { label: "Familia", value: "Tanques" },
    ],
    images: ["/images/inventario/art-34-45.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "35",
    slug: "tanque-industrial-art-35",
    name: "Tanque Industrial — Art. 35",
    condition: "usada",
    category: "tanques",
    brand: "Consultar",
    articleNumber: 35,
    description: "muy buen estado",
    specifications: [
      { label: "Material constructivo", value: "Acero Inoxidable" },
      { label: "Dimensiones", value: "5000 litros: diametro 1.3 mts alt aprox 4 mts" },
      { label: "Familia", value: "Tanques" },
    ],
    images: ["/images/inventario/art-35-46.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "36",
    slug: "tanque-industrial-art-36",
    name: "Tanque Industrial — Art. 36",
    condition: "usada",
    category: "tanques",
    brand: "Consultar",
    articleNumber: 36,
    description: "Equipo usado de la familia Tanques. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "Acero Inoxidable" },
      { label: "Dimensiones", value: "Camara flash: dimensiones aprox 1mts diametro por 2 de altura" },
      { label: "Familia", value: "Tanques" },
    ],
    images: ["/images/inventario/art-36-47.jpg", "/images/inventario/art-36-48.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "37",
    slug: "tanque-industrial-art-37",
    name: "Tanque Industrial — Art. 37",
    condition: "usada",
    category: "tanques",
    brand: "Consultar",
    articleNumber: 37,
    description: "Equipo usado de la familia Tanques. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "Acero Inoxidable" },
      { label: "Dimensiones", value: "15000 litros:_ Diametro 2.7: altura aprox 2,5 mts" },
      { label: "Familia", value: "Tanques" },
    ],
    images: ["/images/inventario/art-37-49.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "38",
    slug: "tanque-industrial-art-38",
    name: "Tanque Industrial — Art. 38",
    condition: "usada",
    category: "tanques",
    brand: "Consultar",
    articleNumber: 38,
    description: "Equipo usado de la familia Tanques. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "Acero Inoxidable" },
      { label: "Dimensiones", value: "7000 litros: diametro 1,7 mts" },
      { label: "Familia", value: "Tanques" },
    ],
    images: ["/images/inventario/art-38-52.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "39",
    slug: "equipo-industrial-transportes-art-39",
    name: "Equipo Industrial — Transportes — Art. 39",
    condition: "usada",
    category: "transportes",
    brand: "Consultar",
    articleNumber: 39,
    description: "Equipo usado de la familia Transportes. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "cinta de 450mm de ancho y 3 mts de largo" },
      { label: "Familia", value: "Transportes" },
    ],
    images: ["/images/inventario/art-39-55.jpg", "/images/inventario/art-39-56.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "40",
    slug: "equipo-industrial-transportes-art-40",
    name: "Equipo Industrial — Transportes — Art. 40",
    condition: "usada",
    category: "transportes",
    brand: "Consultar",
    articleNumber: 40,
    description: "Equipo usado de la familia Transportes. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "cinta de 600 mm de ancho x 3 mts de largo" },
      { label: "Familia", value: "Transportes" },
    ],
    images: ["/images/inventario/art-40-57.jpg", "/images/inventario/art-40-58.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "41",
    slug: "equipo-industrial-transportes-art-41",
    name: "Equipo Industrial — Transportes — Art. 41",
    condition: "usada",
    category: "transportes",
    brand: "Consultar",
    articleNumber: 41,
    description: "Equipo usado de la familia Transportes. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "cinta de 600 mm de ancho x 3 mts de largo" },
      { label: "Familia", value: "Transportes" },
    ],
    images: ["/images/inventario/art-41-59.jpg", "/images/inventario/art-41-60.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "42",
    slug: "ventilador-industrial-art-42",
    name: "Ventilador Industrial — Art. 42",
    condition: "usada",
    category: "ventiladores",
    brand: "Consultar",
    articleNumber: 42,
    description: "buen estado: sin motor: consultar",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "Salida 200x200 mm: dia entrada 300 mm diametro rotor: 600 mm" },
      { label: "Familia", value: "Ventiladores" },
    ],
    images: ["/images/inventario/art-42-61.jpg", "/images/inventario/art-42-62.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "43",
    slug: "intercambiador-de-calor-casco-y-tubo-art-43",
    name: "Intercambiador de Calor Casco y Tubo — Art. 43",
    condition: "usada",
    category: "intercambiadores-de-calor",
    brand: "Consultar",
    articleNumber: 43,
    description: "Equipo usado de la familia Intercambiadores de Calor. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "Acero Inoxidable" },
      { label: "Dimensiones", value: "casco y tubo: dos equipos" },
      { label: "Familia", value: "Intercambiadores de Calor" },
    ],
    images: ["/images/inventario/art-43-63.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "44",
    slug: "bomba-centrifuga-art-44",
    name: "Bomba Centrífuga — Art. 44",
    condition: "usada",
    category: "bombas",
    subcategory: "Centrifugas",
    brand: "Consultar",
    articleNumber: 44,
    description: "Bomba Completa: a revisar",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "Bomba de doble succion: 6x4-14\"" },
      { label: "Familia", value: "Bombas" },
      { label: "Subfamilia", value: "Centrifugas" },
    ],
    images: ["/images/inventario/art-44-64.jpg"],
    featured: true,
    availability: "Disponible",
    price: null,
  },
  {
    id: "45",
    slug: "bomba-centrifuga-art-45",
    name: "Bomba Centrífuga — Art. 45",
    condition: "usada",
    category: "bombas",
    subcategory: "Centrifugas",
    brand: "Consultar",
    articleNumber: 45,
    description: "Equipo usado de la familia Bombas, subfamilia Centrifugas. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "2x3-8" },
      { label: "Familia", value: "Bombas" },
      { label: "Subfamilia", value: "Centrifugas" },
    ],
    images: ["/images/inventario/art-45-65.jpg", "/images/inventario/art-45-66.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "46",
    slug: "bomba-centrifuga-art-46",
    name: "Bomba Centrífuga — Art. 46",
    condition: "usada",
    category: "bombas",
    subcategory: "Centrifugas",
    brand: "Consultar",
    articleNumber: 46,
    description: "Muy buen estado",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "4x6-13" },
      { label: "Familia", value: "Bombas" },
      { label: "Subfamilia", value: "Centrifugas" },
    ],
    images: ["/images/inventario/art-46-68.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "47",
    slug: "bomba-centrifuga-art-47",
    name: "Bomba Centrífuga — Art. 47",
    condition: "usada",
    category: "bombas",
    subcategory: "Centrifugas",
    brand: "Consultar",
    articleNumber: 47,
    description: "Usada completa a revisar",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "3x4-13\"" },
      { label: "Familia", value: "Bombas" },
      { label: "Subfamilia", value: "Centrifugas" },
    ],
    images: ["/images/inventario/art-47-69.jpg", "/images/inventario/art-47-70.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "48",
    slug: "bomba-centrifuga-art-48",
    name: "Bomba Centrífuga — Art. 48",
    condition: "usada",
    category: "bombas",
    subcategory: "Centrifugas",
    brand: "Consultar",
    articleNumber: 48,
    description: "Usada completa a revisar",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "2x3-13" },
      { label: "Familia", value: "Bombas" },
      { label: "Subfamilia", value: "Centrifugas" },
    ],
    images: ["/images/inventario/art-48-71.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "49",
    slug: "bomba-centrifuga-art-49",
    name: "Bomba Centrífuga — Art. 49",
    condition: "usada",
    category: "bombas",
    subcategory: "Centrifugas",
    brand: "Consultar",
    articleNumber: 49,
    description: "Usada completa a revisar",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "4x6-13\"" },
      { label: "Familia", value: "Bombas" },
      { label: "Subfamilia", value: "Centrifugas" },
    ],
    images: ["/images/inventario/art-49-75.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "50",
    slug: "lote-de-correas-varias-art-50",
    name: "Lote de Correas Varias — Art. 50",
    condition: "usada",
    category: "otros-equipos",
    brand: "Consultar",
    articleNumber: 50,
    description: "consultar por lote",
    specifications: [
      { label: "Dimensiones", value: "Correas varias" },
      { label: "Familia", value: "Otros Equipos" },
    ],
    images: ["/images/inventario/art-50-76.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "51",
    slug: "bomba-centrifuga-art-51",
    name: "Bomba Centrífuga — Art. 51",
    condition: "usada",
    category: "bombas",
    subcategory: "Centrifugas",
    brand: "Consultar",
    articleNumber: 51,
    description: "Usada completa a revisar",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "3x4-13\"" },
      { label: "Familia", value: "Bombas" },
      { label: "Subfamilia", value: "Centrifugas" },
    ],
    images: ["/images/inventario/art-51-77.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "52",
    slug: "motorreductor-art-52",
    name: "Motorreductor — Art. 52",
    condition: "usada",
    category: "motorreductores",
    brand: "Consultar",
    articleNumber: 52,
    description: "consultar",
    specifications: [
      { label: "Dimensiones", value: "Sumitomo 10 HP" },
      { label: "Familia", value: "Motorreductores" },
    ],
    images: ["/images/inventario/art-52-78.jpg"],
    featured: true,
    availability: "Disponible",
    price: null,
  },
  {
    id: "53",
    slug: "motorreductor-art-53",
    name: "Motorreductor — Art. 53",
    condition: "usada",
    category: "motorreductores",
    brand: "Consultar",
    articleNumber: 53,
    description: "consultar",
    specifications: [
      { label: "Dimensiones", value: "Equipo varios" },
      { label: "Familia", value: "Motorreductores" },
    ],
    images: ["/images/inventario/art-53-79.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "54",
    slug: "motor-electrico-art-54",
    name: "Motor Eléctrico — Art. 54",
    condition: "usada",
    category: "motores",
    brand: "Consultar",
    articleNumber: 54,
    description: "consultar",
    specifications: [
      { label: "Dimensiones", value: "motores chicos varios" },
      { label: "Familia", value: "Motores" },
    ],
    images: ["/images/inventario/art-54-80.jpg", "/images/inventario/art-54-82.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "55",
    slug: "bomba-centrifuga-art-55",
    name: "Bomba Centrífuga — Art. 55",
    condition: "usada",
    category: "bombas",
    subcategory: "Centrifugas",
    brand: "Consultar",
    articleNumber: 55,
    description: "Equipo usado de la familia Bombas, subfamilia Centrifugas. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "1x2-8\" con motor de 10 HP" },
      { label: "Familia", value: "Bombas" },
      { label: "Subfamilia", value: "Centrifugas" },
    ],
    images: ["/images/inventario/art-55-81.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "56",
    slug: "accesorios-de-piping-art-56",
    name: "Accesorios de Piping — Art. 56",
    condition: "usada",
    category: "piping",
    brand: "Consultar",
    articleNumber: 56,
    description: "consultar",
    specifications: [
      { label: "Material constructivo", value: "Acero Inoxidable" },
      { label: "Dimensiones", value: "accesorios varios 3\"" },
      { label: "Familia", value: "Piping" },
    ],
    images: ["/images/inventario/art-56-83.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "57",
    slug: "valvula-esclusa-art-57",
    name: "Válvula Esclusa — Art. 57",
    condition: "usada",
    category: "piping",
    subcategory: "Valvulas Exclusas",
    brand: "Consultar",
    articleNumber: 57,
    description: "buen buen estado",
    specifications: [
      { label: "Material constructivo", value: "Acero al Carbono" },
      { label: "Dimensiones", value: "3\"" },
      { label: "Familia", value: "Piping" },
      { label: "Subfamilia", value: "Valvulas Exclusas" },
    ],
    images: ["/images/inventario/art-57-84.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "58",
    slug: "accesorios-de-piping-art-58",
    name: "Accesorios de Piping — Art. 58",
    condition: "nueva",
    category: "piping",
    brand: "Consultar",
    articleNumber: 58,
    description: "Consultar por diferentes medidas",
    specifications: [
      { label: "Dimensiones", value: "Accesorios AISI varios" },
      { label: "Familia", value: "Piping" },
    ],
    images: ["/images/inventario/art-58-85.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "59",
    slug: "pistones-neumaticos-art-59",
    name: "Pistones Neumáticos — Art. 59",
    condition: "usada",
    category: "otros-equipos",
    subcategory: "Pistones neumaticos",
    brand: "Consultar",
    articleNumber: 59,
    description: "consultar por distintas medidas",
    specifications: [
      { label: "Dimensiones", value: "Pistones neumaticos varios" },
      { label: "Familia", value: "Otros Equipos" },
      { label: "Subfamilia", value: "Pistones neumaticos" },
    ],
    images: ["/images/inventario/art-59-86.jpg"],
    featured: false,
    availability: "Disponible",
    price: null,
  },
  {
    id: "60",
    slug: "bomba-de-vacio-art-60",
    name: "Bomba de Vacío — Art. 60",
    condition: "usada",
    category: "bombas",
    subcategory: "Vacio",
    brand: "Consultar",
    articleNumber: 60,
    description: "Origen Japon:",
    specifications: [
      { label: "Dimensiones", value: "Bomba de vacio de 30HP x980 rpm" },
      { label: "Familia", value: "Bombas" },
      { label: "Subfamilia", value: "Vacio" },
    ],
    images: ["/images/inventario/art-60-87.jpg", "/images/inventario/art-60-88.jpg", "/images/inventario/art-60-89.jpg", "/images/inventario/art-60-90.jpg"],
    featured: true,
    availability: "Disponible",
    price: null,
  },
  {
    id: "61",
    slug: "generador-eolico-vertical-art-61",
    name: "Generador Eólico Vertical — Art. 61",
    condition: "nueva",
    category: "otros-equipos",
    subcategory: "Generadores Eolicos",
    brand: "Consultar",
    articleNumber: 61,
    description: "Equipo nuevo de la familia Otros Equipos, subfamilia Generadores Eolicos. Consultar disponibilidad y condiciones.",
    specifications: [
      { label: "Dimensiones", value: "Generador elolico vertical" },
      { label: "Familia", value: "Otros Equipos" },
      { label: "Subfamilia", value: "Generadores Eolicos" },
    ],
    images: ["/images/inventario/art-61-91.jpg"],
    featured: true,
    availability: "Disponible",
    price: null,
  },
  {
    id: "62",
    slug: "bomba-centrifuga-art-62",
    name: "Bomba Centrífuga — Art. 62",
    condition: "usada",
    category: "bombas",
    subcategory: "Centrifugas",
    brand: "Consultar",
    articleNumber: 62,
    description: "Bomba en restauracion: Arenado , pintura, rodamientos y retenes: completa.. Buen estado",
    specifications: [
      { label: "Dimensiones", value: "Bomba 8x8-14" },
      { label: "Familia", value: "Bombas" },
      { label: "Subfamilia", value: "Centrifugas" },
    ],
    images: ["/images/inventario/art-62-92.jpg", "/images/inventario/art-62-93.jpg", "/images/inventario/art-62-94.jpg"],
    featured: true,
    availability: "Disponible",
    price: null,
  },
];

// ---------------------------------------------------------------------------
// HELPERS
// ---------------------------------------------------------------------------
export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getCategoryBySlug(slug: string) {
  return categories.find((c) => c.slug === slug);
}

export function getRelatedProducts(product: Product, limit = 4) {
  return products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, limit);
}

export function countByCategory(categorySlug: string) {
  return products.filter((p) => p.category === categorySlug).length;
}

export const brands = Array.from(new Set(products.map((p) => p.brand))).sort();
